theme: jekyll-theme-minimal 
#remote_theme: no-style-please
github:
  me_on_github: https://github.com/saifshahriar
  repository_url: https://github.com/saifshahriar/saifshahriar.github.io
  zip_url: http://example.com/download.zip
