baseurl = "https://example.com/"
languageCode = "en-us"
theme = "nostyleplease"
pagination.pagerSize = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  [params.theme_config]
    appearance = "auto"
    back_home_text = ".."
    date_format = "2006-01-02"
    isListGroupByDate = false
[taxonomies]
  category = 'categories'
  tag = 'tags'
# [params]
#   contentTypeName = "posts"
#   showMenuItems = 2
#   showLanguageSelector = false
#   fullWidthTheme = false
#   centerTheme = true
#
# [languages]
#   [languages.en]
#     title = "Saif Shahriar"
#     subtitle = "A simple, retro theme for Hugo"
#     keywords = ""
#     copyright = ""
#     menuMore = "Show more"
#     readMore = "Read more"
#     readOtherPosts = "Read other posts"
#
#     [languages.en.params.logo]
#       logoText = "Saif Shahriar"
#       logoHomeLink = "/"
#
#     [languages.en.menu]
#       [[languages.en.menu.main]]
#         identifier = "blogs"
#         name = "Blogs"
#         url = "/blogs/"
#       [[languages.en.menu.main]]
#         identifier = "books"
#         name = "Books"
#         url = "/books/"
#       [[languages.en.menu.main]]
#         identifier = "projects"
#         name = "Projects"
#         url = "/projects/"
#     #   [[languages.en.menu.main]]
#     #     identifier = "showcase"
#     #     name = "Showcase"
#     #     url = "/showcase"
